In [1]:
import pandas as pd

In [3]:
path = '../dataset/all_beauty.parquet'
df = pd.read_parquet(path)

In [4]:
df = df.sample(n=min(50, df.shape[0]), random_state=42).reset_index(drop=True)

In [12]:
from transformers import pipeline

# Load the end-to-end ABSA pipeline
absa_pipeline = pipeline(
    "token-classification",
    model="yangheng/deberta-v3-base-end2end-absa",
    aggregation_strategy="simple" # Groups sub-tokens into whole words
)
aspects = []
for text in df['review'].to_list():
    # Run inference
    predictions = absa_pipeline(text)

    # Post-process the output to make it readable
    item_aspect = []
    for pred in predictions:
        label = pred["entity_group"]
        if label == "O":
            continue

        # Labels look like 'B-ASP-Positive' or 'I-ASP-Negative'
        sentiment = label.split("-")[-1]

        item_aspect.append({
            "aspect": pred["word"],
            "sentiment": sentiment,
            "score": round(pred["score"], 4)
        })

    aspects.append(item_aspect)

Device set to use cuda:0
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [65]:
df_own = pd.read_csv('data/new_aspects_sent.csv')

In [72]:
item = 2
print(df.loc[item]['review'])
aspects[item]

Great movie, disc was delivered as expected.

[{'aspect': 'movie', 'sentiment': 'Positive', 'score': np.float32(0.7024)}]

In [73]:
df_own[df_own['review_idx'] == item]

,review_idx,cluster,aspect,sentiment,mentions,confidence,prob_pos,prob_neu,prob_neg
3,2,0,disc,positive,1,0.986,0.986,0.012,0.002

In [5]:
df

,rating,title,text,asin,parent_asin,user_id,timestamp,userId,itemId
0,1,Deceiving.,All shimmer/sparkles... I’ve used Essie all my...,B07L8K15KD,B07L8K15KD,AGMB4OZ76Q426XQV2UIIXXSMTWAQ,2019-05-24 23:59:30.006,405577,57904
1,1,Not for sensitive skin,"I reseived it, used it. Now I'm healing burns ...",B0052YFCSO,B0052YFCSO,AHXZS7TPDISOIXLD2MPRF7I6Q4PQ,2013-04-24 19:42:41.000,622223,4366
2,4,Definitely amazing but still too expensive.,"This face oil is perfect for my skin type,it i...",B08DXZ5VXB,B08DXZ5VXB,AF4T3AQXLGSWBXPJV3RI2DBPEYUA,2020-10-22 02:39:41.956,171674,86097
3,5,Nice product,Very cute! Love it!,B07XKN4F8Z,B07XKN4F8Z,AH2TKN5IY45HAG777EWBYLRSPMZQ,2020-10-04 23:42:13.298,477564,70193
4,5,The backs of my hands are in &lt;3 with these ...,I get my nails did every 2-4 weeks. The variou...,B00QJ7NOMO,B00QJ7NOMO,AG7NRXCOUMI7JOXYP5X446EBNE4Q,2016-12-06 18:40:38.000,343287,14840
5,5,Lives up to description.,Good quality for price. Very pleased. The only...,B0719KWG8H,B09X9BG4FC,AER55MTJS76NFWM3UHZJWCM7F5BA,2021-10-20 16:44:09.470,114337,109536
6,2,Strong gel top coat needed,"Looks fake, add decorations like jewels and a ...",B07DRC4LXV,B07F18W9BT,AHMDLJYCEG2J2HMP3XFDPCGRXODQ,2019-09-09 23:55:16.268,564343,51143
7,5,I love this product,"I love this product! Smells wonderful, between...",B00DT4757A,B00DT4757A,AGNBQE3TIE2JGDRPWMFOPXGHJ7FA,2015-07-16 19:12:19.000,410538,8159
8,4,Cell Perfex Review,This was my first time using a cellulite cream...,B00O14F3WG,B00O14F3WG,AFVH6HPBOPMNOKLW7CPT7XMKNGTA,2014-11-23 01:07:07.000,293064,13720
9,2,Mi opinion,El color no era como esperaba no me gustó lo s...,B09P51BFWM,B09P51BFWM,AHQNOPYHPQCMUYPNDSTSZBDFHHLQ,2023-02-06 21:15:12.709,585752,108282
10,5,Five Stars,Good value!!!,B00K8ODW6M,B00K8ODW6M,AGUSA3UN56ZEBTVDBUBM6SZENHVA,2018-01-09 02:44:08.205,447517,11465
11,5,These bath bombs are awesome. They don't fill ...,These bath bombs are awesome. They don't fill ...,B010TQC4R6,B010TQC4R6,AENB7B5XXHIQUTHEARYQP2OU7NVQ,2016-01-14 23:00:12.000,95197,18655
12,3,My order arrived defective,My product arrived a bit broken. One of the nu...,B071ZRZTKG,B071ZRZTKG,AH6N3GT3OQWMYURB35HAHXZVPYNQ,2018-10-10 10:41:28.229,496498,38562
13,2,Ok,Ok,B08L5KN7X4,B08L5KN7X4,AGZ6XESJJHRDHXZPPBZSRTK3OLJQ,2021-07-24 00:52:07.703,469500,91120
14,4,Perfume skeptic,"I am not a perfume type. Never have been, but ...",B00JAR63VO,B00JAR63VO,AGJ7AS7IRKAHT4B3WQ7TMNIMUVKQ,2016-08-14 14:02:21.000,390626,10881
15,4,Great!,I wish the hair wasn't so thin but other than ...,B010V09Y4Q,B010V09Y4Q,AGQNJPIIDEVEGORCIKUEOYCTBHVQ,2015-12-21 17:42:42.000,427168,18675
16,5,Great for body,Love it. It just delay coming.,B06X912QZP,B06X912QZP,AF67VQ75JH5O46Y3RI3TICNPAK5Q,2021-04-07 22:30:32.297,178466,35649
17,2,Comical,Meant for a gift... I'd be offended if I got t...,B01MRZV3J2,B07J21B7WK,AHTTYYEGGLHA6TJPWPIYODAQZJCQ,2018-11-09 08:49:04.531,601691,55212
18,2,"Sheds, tangles, not heat resistant",Loved the color and the lace front but hated e...,B019VRCPJ6,B019VRCPJ6,AGIN55VBS7STFLGLVAJDSMVK6PSA,2018-01-26 05:42:44.354,387797,22709
19,5,Awesome product,Arrived earlier than expected. Looks exactly t...,B08FT83KPY,B08FT83KPY,AFFMQ3SH7MVDF4DYLMTFJINZ6J4Q,2021-01-10 19:21:28.222,215182,87091
20,5,Very nice for gift - great quality,Very nice item to gift for bearded men - brush...,B00X5U8D6U,B00X5U8D6U,AFVKASRN7OGEOCANWC4YA2TGQLCA,2015-06-29 18:17:55.000,293500,17296
21,5,Good for Retrobriting,I used this stuff to retrobrite electronics (m...,B07B3DVH6K,B07B3DVH6K,AHDDBAU2D3HVXT2326RVYHFHNFEQ,2020-03-02 04:29:09.266,519578,46984
22,4,Whiter teeth after first use!,I was a bit hesitant to try this kit because i...,B00915GCW0,B00915GCW0,AGQZKIXZQSHLK4FKABEI2AUJX3NQ,2016-02-17 04:32:51.000,429039,6113
23,5,Halal hassle free,Most versatile and Muslim friendly. The best ...,B07SXB2LDR,B07SXB2LDR,AFVDOJMV6PDCRA2G3XCMPFEX2UGQ,2019-09-19 17:17:26.497,292531,65598
24,4,not for me,"I do like Shamanuti products, they smell great...",B01BMXXROE,B01BMXXROE,AG5KJ3Z4ZCRHO2GH7YT5Y7CVXPXQ,2016-03-01 20:01:44.000,333080,23728
25,5,The best sampler!,I love all these lotions - but like to sample ...,B071G3THMC,B071G3THMC,AEZTV62LYHY5QFDFUTYF5QVCLGHQ,2022-07-17 04:42:20.725,157106,37785
26,5,Cool,"I gotta say, I really love this case. The only...",B00KL1RCU4,B00KL1RCU4,AGRIAHAJGHIWJ2YXXR5LIPDW2JJQ,2016-02-19 16:27:42.000,431280,11710
27,4,Good bang for your buck,It was super itchy and not very comfortable di...,B00FBGIXUC,B00FBGIXUC,AGZHSNRHYAOLOVETGHF3RXFOXN4Q,2021-11-06 21:10:22.499,470841,8779
28,5,So cute but confusing,I ordered two different lashes from this compa...,B08HJYBFZV,B08HJYBFZV,AFAU5ADXHNGLE22RJVM4KHFSOYTA,2020-11-18 02:47:29.961,191491,88846
29,5,Keeps oil/no leak,Got this for my oldest son. He is touch on oi...,B004YWAZHI,B004YWAZHI,AHRSVY5N5FXO475F3MBA2BYZVNGQ,2020-02-10 21:54:43.231,591558,4280
30,3,Nice but pricey,Quite pricey,B01839XFUG,B01839XFUG,AFL7J5RWVJKMS3SLIJPM6NOYD7VQ,2016-09-01 03:59:15.000,242778,21735
31,1,Burned my eyes,I purchased these makeup removing wipes becaus...,B01MXLP1T1,B01MXLP1T1,AELNWLYT4JFTC6Q46IVKHVIMDQIQ,2019-05-01 21:49:10.107,87304,33593
32,3,NOT 42 INCHES,Not 42 inches,B07Y8TLYPT,B07Y8TLYPT,AE7JFBVQOS6BPHPQLSLYID3UGECQ,2020-08-22 23:39:32.480,27001,70945
33,3,It does not give as strong of a curl as ...,It does not give as strong of a curl as my las...,B000NWMOBS,B000NWMOBS,AEJAKR7KNYPAVPOEJN6W2TDZXWIA,2018-04-29 13:36:35.993,75223,950
34,5,love it!,nothing,B07F6BJLLV,B07F6BJLLV,AHYAU47QIRG7FVMQMPJMTKVF6CYA,2019-05-03 19:33:37.436,623277,51397
35,5,Five Stars,Great product!,B00N11BR2A,B00N11BR2A,AFKAFRZ7XTIAYOAE3QJC2Y6OMXSA,2018-04-10 02:12:49.264,238019,13078
36,5,really nice brand of fractionated coconut oil,just tried this and this brand is really nice.,B01I2MU2JQ,B01I2MU2JQ,AHIHNNKCRC44HGN7OYWZCCALIAWQ,2018-02-03 18:27:05.325,545151,28558
37,5,Holds Hair,It holds my thick hair beautifully.,B075YDL6JV,B075YDL6JV,AEP6L2DPAJXZ4DFMOPIRO3CAGJDA,2020-05-06 00:30:36.496,104789,42770
38,1,Horrible,"Not even what it looks like in the photo, don’...",B0BQWG4K9V,B0BQWG4K9V,AFBBPFIMH75YIKMGYZ4UGBJEXQ4A,2023-02-07 23:06:37.143,193638,112170
39,5,My New Favorite Lashes,These lashes are so lightweight and pretty. C...,B093PYNN5W,B093PYNN5W,AG3Q6SXZPMXGE3I4EPKV447CTVZQ,2022-01-22 03:48:48.853,324078,101189
40,5,Great easy way to dry your hair after shower,Well made and soft and nicely packaged glad ...,B07PJTVNDN,B07PJTVNDN,AE3C2I5J32BUZQNF73SY6ZTXEMMQ,2019-10-18 21:50:15.655,6093,61212
41,5,Love this hair product,Love this hair product. It does a fantastic j...,B00RAMAHA4,B00RAMAHA4,AEGUCQBKHT7HNDUJCA7WI7BBJ2HQ,2015-02-10 20:12:32.000,63466,15087
42,2,help!,How do you get this crap out of your hair once...,B001540XWK,B001540XWK,AH5KMZRW5JRT5X327HOJOJQ4A4LA,2011-04-01 02:43:24.000,491138,1566
43,5,Travel size hair straightener,"I have a natural long curly hair, if I don’t t...",B08H8K4KJB,B08H8K4KJB,AFPFMLP6HINFGHRCK5ZOWCVBBO7Q,2020-10-07 13:50:47.851,263243,88607
44,4,Easy to use.,The product leaves your hair feeling softer an...,B07ZWTYC96,B07ZWTYC96,AFCRKHQF5VC34IZG52CFX7GHYTLA,2020-01-11 07:51:25.712,201002,72794
45,5,Eyelash Growth Serum,After two weeks of continuous use. I am starti...,B011JG1K3E,B011JG1K3E,AHMIR2M7HL2T4OAIFVAOON3CD2SA,2016-03-12 16:08:22.000,565155,18911
46,5,Loved them exactly what i wanted!!,Loved them!!,B08FSZGB7G,B08FSZGB7G,AG3QBYBH4WBXUMDMZFBC22J4IDUQ,2021-04-01 06:15:26.105,324095,87065
47,5,Five Stars,Really soft and the price is the best,B0042T0HLM,B0042T0HLM,AFSNCWK2OXC252YCILS3SBGEZM4A,2015-02-06 19:57:40.000,279139,3549
48,5,STUNNING!,I'm going to try to give as much info as possi...,B0BS1NFPHF,B0BS1R47M7,AHESJW7W2QE35G676MJ5DRMI7JHQ,2023-04-05 03:14:10.863,526944,112223
49,4,Nice for the price,Christmas present for my teenager. She really ...,B00D6OEMBK,B00D6OEMBK,AHSSZUC4CGI75343N3I6BP3DIALQ,2013-12-26 15:26:16.000,596553,7951

In [71]:
df_own

,review_idx,cluster,aspect,sentiment,mentions,confidence,prob_pos,prob_neu,prob_neg
0,0,0,kid,positive,12,0.933750,0.933750,0.058500,0.007917
1,0,1,oval order,positive,1,0.985000,0.985000,0.013000,0.002000
2,1,0,season,positive,1,0.988000,0.988000,0.010000,0.002000
3,2,0,disc,positive,1,0.986000,0.986000,0.012000,0.002000
4,3,0,great writing,positive,1,0.953000,0.953000,0.038000,0.009000
5,4,0,shipment,negative,14,0.655286,0.027429,0.421429,0.550929
6,5,0,extent,positive,11,0.655545,0.619818,0.370636,0.009364
7,6,0,face muscle,positive,2,0.970000,0.970000,0.027500,0.002500
8,7,0,problem,positive,6,0.903667,0.903667,0.083167,0.013333
9,8,0,price,positive,1,0.915000,0.915000,0.082000,0.003000
10,11,0,daughter,positive,3,0.954667,0.954667,0.043333,0.002000
11,14,0,""" new "" dvd set",negative,5,0.605800,0.121400,0.462400,0.416200
12,15,0,guy,positive,7,0.776571,0.522000,0.308429,0.169714
13,16,0,scruff mark,neutral,1,0.878000,0.054000,0.878000,0.068000
14,17,0,anatomy,neutral,4,0.585500,0.251250,0.500000,0.248750
15,21,0,only film version,positive,40,0.823750,0.622350,0.348525,0.029075
16,22,0,master performer,positive,1,0.923000,0.923000,0.070000,0.007000
17,22,2,signature number,positive,1,0.949000,0.949000,0.048000,0.003000
18,23,0,plot,positive,4,0.977500,0.977500,0.019250,0.003000
19,25,0,very intreste script,positive,2,0.980000,0.980000,0.018000,0.002000
20,26,0,end,positive,1,0.971000,0.971000,0.025000,0.004000
21,27,0,great theme,positive,7,0.650143,0.319000,0.241714,0.439429
22,27,3,same corrupt officer,negative,1,0.698000,0.072000,0.230000,0.698000
23,29,0,low expectation,negative,1,0.735000,0.019000,0.246000,0.735000
24,31,0,absolute favorite,positive,5,0.773400,0.718600,0.163000,0.118400
25,32,0,loss,positive,6,0.961500,0.961500,0.034833,0.003833
26,33,0,cinematography,neutral,41,0.696610,0.164000,0.601488,0.234561
27,33,4,gold standard,neutral,1,0.838000,0.107000,0.838000,0.055000
28,34,0,history,positive,1,0.913000,0.913000,0.080000,0.006000
29,35,0,time,positive,2,0.796500,0.481500,0.177500,0.341000
30,36,0,dvd,negative,7,0.775857,0.015714,0.227857,0.756429
31,37,0,journey,positive,10,0.972400,0.972400,0.025500,0.002100
32,38,0,action,positive,1,0.987000,0.987000,0.011000,0.002000
33,41,0,dvd,positive,4,0.971500,0.971500,0.026500,0.002000
34,43,0,classic,positive,5,0.954600,0.954600,0.040000,0.005400
35,44,0,very classy angel,positive,1,0.979000,0.979000,0.018000,0.003000
36,45,0,woman,negative,1,0.929000,0.006000,0.065000,0.929000
37,46,0,second time,positive,1,0.577000,0.577000,0.413000,0.010000
38,47,0,scene,neutral,5,0.512600,0.017200,0.505200,0.477600
39,47,5,russian embassy,neutral,1,0.519000,0.017000,0.519000,0.464000
40,48,0,close friend,neutral,6,0.668833,0.426500,0.545500,0.028000
41,49,0,first time,positive,1,0.987000,0.987000,0.011000,0.002000