In [6]:
import pandas as pd

In [34]:
path = '../../dataset/amazon.parquet'
df = pd.read_parquet(path)

In [35]:
df = df.sample(n=min(50, df.shape[0]), random_state=42).reset_index(drop=True)

In [12]:
from transformers import pipeline

# Load the end-to-end ABSA pipeline
absa_pipeline = pipeline(
    "token-classification",
    model="yangheng/deberta-v3-base-end2end-absa",
    aggregation_strategy="simple" # Groups sub-tokens into whole words
)
aspects = []
for text in df['review'].to_list():
    # Run inference
    predictions = absa_pipeline(text)

    # Post-process the output to make it readable
    item_aspect = []
    for pred in predictions:
        label = pred["entity_group"]
        if label == "O":
            continue

        # Labels look like 'B-ASP-Positive' or 'I-ASP-Negative'
        sentiment = label.split("-")[-1]

        item_aspect.append({
            "aspect": pred["word"],
            "sentiment": sentiment,
            "score": round(pred["score"], 4)
        })

    aspects.append(item_aspect)

Device set to use cuda:0
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [65]:
df_own = pd.read_csv('data/new_aspects_sent.csv')

In [72]:
item = 2
print(df.loc[item]['review'])
aspects[item]

Great movie, disc was delivered as expected.

[{'aspect': 'movie', 'sentiment': 'Positive', 'score': np.float32(0.7024)}]

In [73]:
df_own[df_own['review_idx'] == item]

,review_idx,cluster,aspect,sentiment,mentions,confidence,prob_pos,prob_neu,prob_neg
3,2,0,disc,positive,1,0.986,0.986,0.012,0.002

In [74]:
aspects

[[{'aspect': 'Price', 'sentiment': 'Neutral', 'score': np.float32(0.7859)},
  {'aspect': 'was', 'sentiment': 'Neutral', 'score': np.float32(0.7164)},
  {'aspect': 'Deli', 'sentiment': 'Neutral', 'score': np.float32(0.4784)},
  {'aspect': 'every', 'sentiment': 'Neutral', 'score': np.float32(0.6554)}],
 [{'aspect': 'series', 'sentiment': 'Positive', 'score': np.float32(0.7082)}],
 [{'aspect': 'movie', 'sentiment': 'Positive', 'score': np.float32(0.7024)}],
 [{'aspect': 'writing', 'sentiment': 'Neutral', 'score': np.float32(0.6935)},
  {'aspect': 'editing', 'sentiment': 'Neutral', 'score': np.float32(0.6812)},
  {'aspect': 'acting', 'sentiment': 'Neutral', 'score': np.float32(0.6853)},
  {'aspect': 'ending', 'sentiment': 'Neutral', 'score': np.float32(0.5841)}],
 [{'aspect': 'picture', 'sentiment': 'Neutral', 'score': np.float32(0.7403)},
  {'aspect': 'sound', 'sentiment': 'Neutral', 'score': np.float32(0.7676)}],
 [{'aspect': 'setting', 'sentiment': 'Neutral', 'score': np.float32(0.4647)},
  {'aspect': 'Days', 'sentiment': 'Neutral', 'score': np.float32(0.5876)}],
 [],
 [{'aspect': 'Martin Sheen',
   'sentiment': 'Negative',
   'score': np.float32(0.5816)}],
 [{'aspect': 'Adam West',
   'sentiment': 'Positive',
   'score': np.float32(0.6207)},
  {'aspect': 'Batman', 'sentiment': 'Neutral', 'score': np.float32(0.4887)}],
 [{'aspect': 'series', 'sentiment': 'Positive', 'score': np.float32(0.6287)}],
 [{'aspect': 'story', 'sentiment': 'Positive', 'score': np.float32(0.8459)}],
 [],
 [],
 [{'aspect': 'Red Oaks',
   'sentiment': 'Positive',
   'score': np.float32(0.9315)}],
 [{'aspect': 'DVD', 'sentiment': 'Neutral', 'score': np.float32(0.454)},
  {'aspect': 'Disc', 'sentiment': 'Neutral', 'score': np.float32(0.5021)},
  {'aspect': '5', 'sentiment': 'Negative', 'score': np.float32(0.4954)}],
 [{'aspect': 'Vines', 'sentiment': 'Neutral', 'score': np.float32(0.516)}],
 [],
 [],
 [{'aspect': 'ending', 'sentiment': 'Negative', 'score': np.float32(0.4833)}],
 [{'aspect': 'movie', 'sentiment': 'Positive', 'score': np.float32(0.928)}],
 [],
 [{'aspect': 'acting', 'sentiment': 'Neutral', 'score': np.float32(0.8754)},
  {'aspect': 'design', 'sentiment': 'Neutral', 'score': np.float32(0.3973)},
  {'aspect': 'costuming', 'sentiment': 'Neutral', 'score': np.float32(0.819)},
  {'aspect': 'Branagh', 'sentiment': 'Neutral', 'score': np.float32(0.8309)},
  {'aspect': 'Hamlet', 'sentiment': 'Neutral', 'score': np.float32(0.5807)},
  {'aspect': 'Jacobi', 'sentiment': 'Neutral', 'score': np.float32(0.8844)},
  {'aspect': 'Claudius', 'sentiment': 'Neutral', 'score': np.float32(0.6537)},
  {'aspect': 'Robin Williams',
   'sentiment': 'Neutral',
   'score': np.float32(0.687)},
  {'aspect': 'setting', 'sentiment': 'Neutral', 'score': np.float32(0.7801)},
  {'aspect': 'ity scene',
   'sentiment': 'Neutral',
   'score': np.float32(0.8192)}],
 [{'aspect': 'performer',
   'sentiment': 'Positive',
   'score': np.float32(0.584)}],
 [{'aspect': 'plot', 'sentiment': 'Negative', 'score': np.float32(0.4792)},
  {'aspect': 'blazing saddles',
   'sentiment': 'Neutral',
   'score': np.float32(0.777)}],
 [{'aspect': 'hilarious',
   'sentiment': 'Positive',
   'score': np.float32(0.7424)}],
 [{'aspect': 'script', 'sentiment': 'Neutral', 'score': np.float32(0.4888)},
  {'aspect': 'acting', 'sentiment': 'Positive', 'score': np.float32(0.4709)}],
 [{'aspect': 'movie', 'sentiment': 'Positive', 'score': np.float32(0.8301)}],
 [{'aspect': 'officers',
   'sentiment': 'Negative',
   'score': np.float32(0.5197)}],
 [{'aspect': 'acting', 'sentiment': 'Positive', 'score': np.float32(0.9048)}],
 [],
 [],
 [],
 [{'aspect': 'dolphin', 'sentiment': 'Neutral', 'score': np.float32(0.69)},
  {'aspect': 'people', 'sentiment': 'Neutral', 'score': np.float32(0.7048)},
  {'aspect': 'marine animal hospital',
   'sentiment': 'Neutral',
   'score': np.float32(0.777)}],
 [{'aspect': 'cinematography',
   'sentiment': 'Neutral',
   'score': np.float32(0.5213)}],
 [{'aspect': 'movie', 'sentiment': 'Positive', 'score': np.float32(0.8589)}],
 [{'aspect': 'Plot', 'sentiment': 'Neutral', 'score': np.float32(0.6668)},
  {'aspect': 'story', 'sentiment': 'Neutral', 'score': np.float32(0.4557)},
  {'aspect': 'acting', 'sentiment': 'Negative', 'score': np.float32(0.4774)},
  {'aspect': 'dialog', 'sentiment': 'Neutral', 'score': np.float32(0.5744)}],
 [{'aspect': 'DVD', 'sentiment': 'Negative', 'score': np.float32(0.8065)}],
 [{'aspect': 'movie', 'sentiment': 'Positive', 'score': np.float32(0.5067)}],
 [{'aspect': 'action', 'sentiment': 'Positive', 'score': np.float32(0.4806)},
  {'aspect': 'Lock', 'sentiment': 'Neutral', 'score': np.float32(0.4845)}],
 [],
 [{'aspect': 'movie', 'sentiment': 'Positive', 'score': np.float32(0.9204)}],
 [{'aspect': 'DVD', 'sentiment': 'Positive', 'score': np.float32(0.8736)}],
 [{'aspect': 'movie', 'sentiment': 'Positive', 'score': np.float32(0.9231)}],
 [{'aspect': 'Blu-ray transfer',
   'sentiment': 'Positive',
   'score': np.float32(0.5712)},
  {'aspect': 'sounds', 'sentiment': 'Neutral', 'score': np.float32(0.4979)}],
 [{'aspect': 'Johnny Maestro',
   'sentiment': 'Positive',
   'score': np.float32(0.8792)}],
 [{'aspect': 'Ashley Darby',
   'sentiment': 'Negative',
   'score': np.float32(0.9362)}],
 [],
 [{'aspect': 'dialog', 'sentiment': 'Neutral', 'score': np.float32(0.4528)}],
 [{'aspect': 'features', 'sentiment': 'Neutral', 'score': np.float32(0.5283)}],
 [{'aspect': 'Diane Franklin',
   'sentiment': 'Positive',
   'score': np.float32(0.8537)}]]

In [71]:
df_own

,review_idx,cluster,aspect,sentiment,mentions,confidence,prob_pos,prob_neu,prob_neg
0,0,0,kid,positive,12,0.933750,0.933750,0.058500,0.007917
1,0,1,oval order,positive,1,0.985000,0.985000,0.013000,0.002000
2,1,0,season,positive,1,0.988000,0.988000,0.010000,0.002000
3,2,0,disc,positive,1,0.986000,0.986000,0.012000,0.002000
4,3,0,great writing,positive,1,0.953000,0.953000,0.038000,0.009000
5,4,0,shipment,negative,14,0.655286,0.027429,0.421429,0.550929
6,5,0,extent,positive,11,0.655545,0.619818,0.370636,0.009364
7,6,0,face muscle,positive,2,0.970000,0.970000,0.027500,0.002500
8,7,0,problem,positive,6,0.903667,0.903667,0.083167,0.013333
9,8,0,price,positive,1,0.915000,0.915000,0.082000,0.003000
10,11,0,daughter,positive,3,0.954667,0.954667,0.043333,0.002000
11,14,0,""" new "" dvd set",negative,5,0.605800,0.121400,0.462400,0.416200
12,15,0,guy,positive,7,0.776571,0.522000,0.308429,0.169714
13,16,0,scruff mark,neutral,1,0.878000,0.054000,0.878000,0.068000
14,17,0,anatomy,neutral,4,0.585500,0.251250,0.500000,0.248750
15,21,0,only film version,positive,40,0.823750,0.622350,0.348525,0.029075
16,22,0,master performer,positive,1,0.923000,0.923000,0.070000,0.007000
17,22,2,signature number,positive,1,0.949000,0.949000,0.048000,0.003000
18,23,0,plot,positive,4,0.977500,0.977500,0.019250,0.003000
19,25,0,very intreste script,positive,2,0.980000,0.980000,0.018000,0.002000
20,26,0,end,positive,1,0.971000,0.971000,0.025000,0.004000
21,27,0,great theme,positive,7,0.650143,0.319000,0.241714,0.439429
22,27,3,same corrupt officer,negative,1,0.698000,0.072000,0.230000,0.698000
23,29,0,low expectation,negative,1,0.735000,0.019000,0.246000,0.735000
24,31,0,absolute favorite,positive,5,0.773400,0.718600,0.163000,0.118400
25,32,0,loss,positive,6,0.961500,0.961500,0.034833,0.003833
26,33,0,cinematography,neutral,41,0.696610,0.164000,0.601488,0.234561
27,33,4,gold standard,neutral,1,0.838000,0.107000,0.838000,0.055000
28,34,0,history,positive,1,0.913000,0.913000,0.080000,0.006000
29,35,0,time,positive,2,0.796500,0.481500,0.177500,0.341000
30,36,0,dvd,negative,7,0.775857,0.015714,0.227857,0.756429
31,37,0,journey,positive,10,0.972400,0.972400,0.025500,0.002100
32,38,0,action,positive,1,0.987000,0.987000,0.011000,0.002000
33,41,0,dvd,positive,4,0.971500,0.971500,0.026500,0.002000
34,43,0,classic,positive,5,0.954600,0.954600,0.040000,0.005400
35,44,0,very classy angel,positive,1,0.979000,0.979000,0.018000,0.003000
36,45,0,woman,negative,1,0.929000,0.006000,0.065000,0.929000
37,46,0,second time,positive,1,0.577000,0.577000,0.413000,0.010000
38,47,0,scene,neutral,5,0.512600,0.017200,0.505200,0.477600
39,47,5,russian embassy,neutral,1,0.519000,0.017000,0.519000,0.464000
40,48,0,close friend,neutral,6,0.668833,0.426500,0.545500,0.028000
41,49,0,first time,positive,1,0.987000,0.987000,0.011000,0.002000