In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('aspects_amazon.parquet')

In [4]:
df.shape

(212, 5)

In [30]:
df_aspects_sent = pd.read_csv('../results/amazon_aspects.csv')

In [35]:
df_aspects_sent

,review_idx,cluster,aspect,sentiment,mentions,confidence,prob_pos,prob_neu,prob_neg
0,0,0,kid,positive,12,0.933750,0.933750,0.058500,0.007917
1,0,1,oval order,positive,1,0.985000,0.985000,0.013000,0.002000
2,1,0,season,positive,1,0.988000,0.988000,0.010000,0.002000
3,2,0,disc,positive,1,0.986000,0.986000,0.012000,0.002000
4,3,0,great writing,positive,1,0.953000,0.953000,0.038000,0.009000
5,4,0,shipment,negative,14,0.655286,0.027429,0.421429,0.550929
6,5,0,extent,positive,11,0.655545,0.619818,0.370636,0.009364
7,6,0,face muscle,positive,2,0.970000,0.970000,0.027500,0.002500
8,7,0,problem,positive,6,0.903667,0.903667,0.083167,0.013333
9,8,0,price,positive,1,0.915000,0.915000,0.082000,0.003000
10,11,0,daughter,positive,3,0.954667,0.954667,0.043333,0.002000
11,14,0,""" new "" dvd set",negative,5,0.605800,0.121400,0.462400,0.416200
12,15,0,guy,positive,7,0.776571,0.522000,0.308429,0.169714
13,16,0,scruff mark,neutral,1,0.878000,0.054000,0.878000,0.068000
14,17,0,anatomy,neutral,4,0.585500,0.251250,0.500000,0.248750
15,21,0,only film version,positive,40,0.823750,0.622350,0.348525,0.029075
16,22,0,master performer,positive,1,0.923000,0.923000,0.070000,0.007000
17,22,2,signature number,positive,1,0.949000,0.949000,0.048000,0.003000
18,23,0,plot,positive,4,0.977500,0.977500,0.019250,0.003000
19,25,0,very intreste script,positive,2,0.980000,0.980000,0.018000,0.002000
20,26,0,end,positive,1,0.971000,0.971000,0.025000,0.004000
21,27,0,great theme,positive,7,0.650143,0.319000,0.241714,0.439429
22,27,3,same corrupt officer,negative,1,0.698000,0.072000,0.230000,0.698000
23,29,0,low expectation,negative,1,0.735000,0.019000,0.246000,0.735000
24,31,0,absolute favorite,positive,5,0.773400,0.718600,0.163000,0.118400
25,32,0,loss,positive,6,0.961500,0.961500,0.034833,0.003833
26,33,0,cinematography,neutral,41,0.696610,0.164000,0.601488,0.234561
27,33,4,gold standard,neutral,1,0.838000,0.107000,0.838000,0.055000
28,34,0,history,positive,1,0.913000,0.913000,0.080000,0.006000
29,35,0,time,positive,2,0.796500,0.481500,0.177500,0.341000
30,36,0,dvd,negative,7,0.775857,0.015714,0.227857,0.756429
31,37,0,journey,positive,10,0.972400,0.972400,0.025500,0.002100
32,38,0,action,positive,1,0.987000,0.987000,0.011000,0.002000
33,41,0,dvd,positive,4,0.971500,0.971500,0.026500,0.002000
34,43,0,classic,positive,5,0.954600,0.954600,0.040000,0.005400
35,44,0,very classy angel,positive,1,0.979000,0.979000,0.018000,0.003000
36,45,0,woman,negative,1,0.929000,0.006000,0.065000,0.929000
37,46,0,second time,positive,1,0.577000,0.577000,0.413000,0.010000
38,47,0,scene,neutral,5,0.512600,0.017200,0.505200,0.477600
39,47,5,russian embassy,neutral,1,0.519000,0.017000,0.519000,0.464000
40,48,0,close friend,neutral,6,0.668833,0.426500,0.545500,0.028000
41,49,0,first time,positive,1,0.987000,0.987000,0.011000,0.002000

In [36]:
df_old = pd.read_csv('../../../aspect_cor-rating/results/amazon_aspects_agg.csv')
df_old.shape

(1378463, 9)

In [22]:
# df_old[df_old['review_idx'].isin(df_aspects_sent['review_idx'].unique())].to_csv('res_old.csv', index=False)

In [40]:
df_old = pd.read_parquet('aspects_amazon.parquet')

In [41]:
df_old

,review_idx,review,aspect,aspect_raw,cluster
0,0,My kids are in love with this show so I had to...,love,love,6
1,0,My kids are in love with this show so I had to...,collection,the collection,7
2,0,My kids are in love with this show so I had to...,junk,the junk,8
3,0,My kids are in love with this show so I had to...,gift,the gift,11
4,0,My kids are in love with this show so I had to...,complete series collection,the complete series collection,12
...,...,...,...,...,...
208,48,I rented this movie and watched it with some c...,football,football,205
209,48,I rented this movie and watched it with some c...,life,life,206
210,48,I rented this movie and watched it with some c...,special feature,the special features,207
211,48,I rented this movie and watched it with some c...,friend,friends,208
212,49,Just finished watching this movie for the firs...,first time,the first time,209

In [50]:
df_aspects = pd.read_csv('../results/amazon_aspects.csv')

In [52]:
df_aspects

,review_idx,cluster,aspect,sentiment,mentions,confidence,prob_pos,prob_neu,prob_neg
0,0,1,love,positive,1,0.987,0.987,0.011,0.002
1,0,2,collection,positive,1,0.937,0.937,0.055,0.008
2,0,3,junk,positive,1,0.594,0.594,0.354,0.052
3,0,6,gift,positive,1,0.985,0.985,0.013,0.002
4,0,7,complete series collection,positive,1,0.983,0.983,0.015,0.002
...,...,...,...,...,...,...,...,...,...
208,48,205,football,neutral,1,0.544,0.440,0.544,0.016
209,48,206,life,neutral,1,0.539,0.444,0.539,0.017
210,48,207,special feature,positive,1,0.868,0.868,0.128,0.004
211,48,208,friend,neutral,1,0.772,0.160,0.772,0.067
212,49,209,first time,positive,1,0.987,0.987,0.011,0.002

In [54]:
df = pd.read_parquet('../../../dataset/amazon.parquet')
df = df.sample(n=min(50, df.shape[0]), random_state=42).reset_index(drop=True)

df['review']

In [56]:
df['review']

0     My kids are in love with this show so I had to...
1     Amazon got it 100% correct! A great series. Lo...
2          Great movie, disc was delivered as expected.
3     Another very good Atom Agoyan film with great ...
4     I'm not so happy now. I received the shipment ...
5     Didn;t like the movie at first, but after view...
6     Your face muscles will ache from the many smil...
7     Despite some problems (Martin Sheen as Lee mak...
8     It was worth the price just to hear Adam West ...
9                                      Excellent series
10                              A good story well done.
11    My daughter loves Daniel Tiger and has learned...
12                                      One of the best
13    Red Oaks Season 1 was so good that it was inev...
14    I ordered a "new" DVD set. It was missing Disc...
15    These are the guys that do all the Vines. I lo...
16    was new and wrapped some scruff marks but shou...
17    I watched this way back when! I loved it then....
18                              Very predictable ending
19                                       Awesome movie!
20                      Very good. I really enjoyed it.
21    This is the only film version of Hamlet I have...
22    What can you say - he was a master performer. ...
23    I really liked Andy Griffith in this movie. Th...
24                            Continues to be hilarious
25    Very intresting script, good acting, was surpr...
26    great movie but I would have liked to see more...
27    A good movie with a great theme. Unfortunately...
28    amazing acting, crazy story but very interesti...
29    I had low expectations to begin with, but it w...
30                                  like it interesting
31    This was an absolute favorite of mine growing ...
32    Great heart warming story about a dolphin adap...
33    The cinematography of much of the film was jus...
34    A good movie. I'm not sure how close to histor...
35    Plot is pretty solid. Seems a little disjointe...
36    DVD had deep scratches in it. Was described as...
37    This is an awesome movie. This movie will make...
38    Great Danish film. This movie is hilarious and...
39    First movie was far better. This one was kind ...
40                  Great movie. Very thought provoking
41    I used the DVD for a Bible study group. It cam...
42                                      Love this movie
43    I won't review the movie itself. It's a classi...
44    A must have for Johnny Maestro fans! Fabulous ...
45    Please get Ashley Darby and her horrible husba...
46    I watched this for the second time tonight, th...
47    In some scenes the acting was stiff. Not due t...
48    I rented this movie and watched it with some c...
49    Just finished watching this movie for the firs...
Name: review, dtype: object

In [ ]:
My kids are in love with this show so I had to get the collection. I rather them watch a holsome show like this then the some of the junk on TV now a days. The kids love the box the DVD's are in. I just made the gift that much more special. For being the complete Series Collection the Price was resonable. Delievery was quick! Got it just in time for my sons birthday! :) Very Happy with the oval order in general!
Amazon got it 100% correct! A great series. Looking forward to season 2.
"Great movie, disc was delivered as expected."
"Another very good Atom Agoyan film with great writing, editing, and acting but with--spoiler alert--an unfortunate Hollywood ending."
"I'm not so happy now. I received the shipment from Mighty Silver on March 29, 2017, and I wish I had watched the Perry Mason movies right away. I have enjoyed watching them but I haven't finished them yet. Tonight I played # 7, The Case of the Poisoned Pen, and when it got almost to the end, in the final courtroom scene, the picture began breaking up, stopping, skipping, and the sound was in and out. I finally took it out of the machine and noticed a place on the back that was defective. It was not a smudge or a scratch. It looked as if there was nothing recorded in that space, but there had to have been something, or I wouldn't have been able to see what little was there. I know it's past the time of being replaced, but is there some way I can get another copy of that DVD? It was frustrating not to be able to see how it ended! I hope whoever reads this can help. Thank you."
"Didn;t like the movie at first, but after viewing several times on VHS, have come to like it. To some extent I've come to like itdue to it's small town setting. Back in the 1970's when my small hometown started what is called ""Sweet Corn Days"", they had a lot going on to having a queen for the weekend in late July, along with a parade of various vehicles and farm tractors. Now that I am back living in my hometown after being away for 42 years, the town's Sweet Corn Days is just a shell of it's former self. So this movie brings back some of those memories!"
Your face muscles will ache from the many smiles this movie will require you to make.Enjoy it.
"Despite some problems (Martin Sheen as Lee makes the General look like a nut!), it still entertained and informed me. Loved that it was filmed at Gettysburg and this allowed the movie to really flesh out The Killer Angels. Little Round Top was an excellent depiction and Picket's Charge gave me the chills."
It was worth the price just to hear Adam West as the real Batman once again.
Excellent series
A good story well done.
My daughter loves Daniel Tiger and has learned a lot from him. We are often singing his songs in our home.
One of the best
Red Oaks Season 1 was so good that it was inevitable that Season 2 would fall below it. I just couldn't believe how much it fell.
"I ordered a ""new"" DVD set. It was missing Disc 1 and Disc 5 was visibly warped on the edge. I've returned it and ordered a new set. I'll re-review when I get the other one!"
"These are the guys that do all the Vines. I love their Vines more than the movie. But, I'm happy to see them getting out there and producing crappy movies. At least they are trying. But, the Vines they do are hilarious. I could watch those for an hour at a time. Idea. They should just do a 90 minute vine movie. It's more believable. When you watch this movie you know they are reading from a script. It isn't as natural as a Vine. But, I'm very happy to see them making crappy movies. I'm inspired. They're getting out there and doing something. I just sit on my ass and eat bon bons."
was new and wrapped some scruff marks but should play as well not tested yet.
"I watched this way back when! I loved it then. I still like it. Here's the thing. They got some of the anatomy wrong. When Jonathan Chase turns into a hawk his hand should change into part of a wing, not a talon. Still good to watch. So was Automan."
Very predictable ending
Awesome movie!
Very good. I really enjoyed it.
"This is the only film version of Hamlet I have seen fully, but I played Horatio in a stage production several years ago, and therefore have a well-rounded knowledge of the play. I would give this film a 8 out of 10 for acting, but 9.5 out of 10 for visual design, costuming, etc. Branagh is a very good Hamlet, Derek Jacobi is probably the best as Claudius, and most of the other cast is passable. The celebrity cameos were fun (Robin Williams is perfect) and harmless (except for Jack Lemmon!) The entire setting has been overhauled to the mid-19th century, which works perfectly fine, except for a few script incongruities (e.g., references to obsolete weapons and Hamlet being attacked by pirates on his way to England). Those who would condemn this change in period may forget that Shakespeare thought nothing of including cannon and other fixtures of his time when writing within ancient and medieval settings. A fresh interpretation of many scenes has been attempted, usually involving mirrors, hidden passages, and people walking through several rooms while they speak--a nice metaphorical addition to the ever-present themes of madness vs. sanity and secrecy vs. innocent ignorance. The climactic ""mortality scene,"" which I like to call it, is excellent--not truly over the top. The actor playing Horatio was solid, and really shined when on the verge of suicide (""I am more an antique Roman than a Dane""). However, the scene that actually made the biggest impression on me was Reynaldo's (Gerard Depardieu) brief interview with Polonius. I won't spoil it other than to say it completely altered my perception of Polonius and added a whole layer of seediness to Laertes' travels in France (and by the way, it appears that he brings Paris Communards or some such folk along with him when returning to Denmark!)"
What can you say - he was a master performer. I have seen better by Sinatra but this one was still good. It includes most all of his signature numbers.
I really liked Andy Griffith in this movie. The plot wasn't super engaging but some of the quips were priceless humor and it makes you want to rewatch blazing saddles if you have watched it already.
Continues to be hilarious
"Very intresting script, good acting, was surprised by the ending"
great movie but I would have liked to see more in the end
"A good movie with a great theme. Unfortunately the US Army was used against it's citizens, the same corrupt officers were used yet again to destroy the horses of the defunct cavalry. While parts of this story are true and parts fictional, the true parts should be a sobering wakeup for the people of today. The US Army should never be told to fire on US citizens, yet this is possible today as people who disagree with policy are branded suspect."
"amazing acting, crazy story but very interesting. highly recommend it"
"I had low expectations to begin with, but it was far from meeting them."
like it interesting
"This was an absolute favorite of mine growing up. They were ahead of their time with this show. Everytime I see a fake supernatural video floating around the internet, I can thank this series for showing me what was real and what was faked."
"Great heart warming story about a dolphin adapting to the loss of her fluke with the help of caring people at a marine animal hospital-based on a true story. Good acting by the seasoned actors as well as the young ones playing Sawyer and Hazel, and the main star, Winter, the dolphin who actually lost her fluke."
"The cinematography of much of the film was just awful. I agree with those who likened it to something shot with an iPhone. I suspect that this was done to imbue a sense of reality to the film's fictional portrayal of Neil Armstrong's personal life. The producers and director chose to focus more on the man and less on the crowning achievement of the American moon landing. Yes, I saw the movie despite its elimination of the symbolic capstone of the US space program - the planting the American Flag on the moon. I should have understood this willful editorial decision for the augury that it was. One would think they would try to represent the man accurately by staying true to Jim Hanson's research that underlied his book First Man. In my opinion and apparently that of many others who knew Armstrong well, this movie is a work of dishonest fiction. I'd provide links but it would violate Amazon's policy. I totally get that adapting a book to the screen is a monumental task. It necessarily requires the producers, writers and directors to distill the book's content to fit in an affordable feature length film. Sometimes they need to take liberties like rethreading its chronology for the sake of continuity and audience engagement. A gold standard for doing this well can be found in the Hanks-Spielberg screenplay adaptation of Stephen Ambrose's book ""Band of Brothers"". Neither the book or their HBO series papered over their subject's flaws or bad decisions. However it did not seek to delegitimize their sacrifices or the significance of their accomplishments either. Most of all, the HBO series honored and respected their service to our country. Contrast this with the First Man adaptation that seems to me to be agenda-driven - designed to take Armstrong down a notch by obsessing on his few flaws and playing down his spectacular achievements. They also diss US space program and our flag. I guess I went expecting too much from a French director (Damien Chazelle) and a Canadian actor (Ryan Gosling). If there's any fondness for Armstrong as a great American hero in this movie, I can't find it."
"A good movie. I'm not sure how close to history, though."
Plot is pretty solid. Seems a little disjointed at times but overall a pretty captivating story. First episode acting was a little weak. Not all characters but the dialog was a little rough. Definitely recommend.
DVD had deep scratches in it. Was described as new. As soon as I loaded DVD it would not play I tried cleaning DVD reloaded an it skipped an paused at very beginning NEVER moving from the scene! Kids were crying the thought they were going to watch an old classic movie!
This is an awesome movie. This movie will make you laugh and maybe cry! It shows the journey of a girl moving from one city to another and how her body and emotions play a roll. My entire family loves it. We watch it all the time together as a family. I love that it has the digital copy too. We put it on my daughters Ipad for traveling in the car on long family trips!
Great Danish film. This movie is hilarious and action packed. If you like Lock Stock or Snatch; You'll like this.
"First movie was far better. This one was kind of boring. Don't expect to be impressed with this movie, but its OK."
Great movie. Very thought provoking
I used the DVD for a Bible study group. It came right on time and worked great at the study.
Love this movie
"I won't review the movie itself. It's a classic, and probably the best of the bunch. The Blu-ray transfer is superb. It looks and sounds like it was just made, which is the main reason to buy a blu ray of an old movie, right? You can watch this and Prometheus side by side, and wonder how 30 years could have passed between them."
A must have for Johnny Maestro fans! Fabulous collection! All my favs. The voice of a very classy angel.
Please get Ashley Darby and her horrible husband off this show. They both are a disrespect to women and the #metoo movement.
"I watched this for the second time tonight, the first being in 2008 while I was living in Paris. Unlike many films, it doesn't seem dated. If anything, I think I appreciated it more this time around."
"In some scenes the acting was stiff. Not due to cultural behavior but in the acting i.e. the 'gang' in East Berlin, the dialogs in the Russian embassy and the family interaction between Tom Hanks and his 'wife'."
"I rented this movie and watched it with some close friends yesterday and just had to watch it a second time today. While the movie is about a football team, it really isn't as much a movie about football as it is about life, our goals, our hopes and dreams. It helps one to reflect upon what is and what is not truly important in life. Whether you rent this or buy this, it is worth watching and be sure to watch the special features. I'm planning to buy this movie and probably an extra copy or two for friends and family."
Just finished watching this movie for the first time in years. still love it. Diane Franklin is beautiful. This could be the best 80's movie! Its definitely the most underrated 80's movie.

In [57]:
pure_mode = pd.read_csv('../../../dataset/amazon_absa_test.csv')

In [58]:
pure_mode

,text,aspects,positions,sentiments,confidence,details
0,My kids are in love with this show so I had to...,"['Price', 'was', 'Deli', 'every']","[[285, 291], [291, 295], [306, 311], [311, 316]]","['Neutral', 'Neutral', 'Neutral', 'Neutral']","[0.7858583927154541, 0.7164409756660461, 0.478...","[{'aspect': 'Price', 'start': 285, 'end': 291,..."
1,Amazon got it 100% correct! A great series. Lo...,['series'],"[[35, 42]]",['Positive'],[0.7082436084747314],"[{'aspect': 'series', 'start': 35, 'end': 42, ..."
2,"Great movie, disc was delivered as expected.",['movie'],"[[5, 11]]",['Positive'],[0.7023565769195557],"[{'aspect': 'movie', 'start': 5, 'end': 11, 'e..."
3,Another very good Atom Agoyan film with great ...,"['writing', 'editing', 'acting', 'ending']","[[45, 53], [54, 62], [67, 74], [124, 131]]","['Neutral', 'Neutral', 'Neutral', 'Neutral']","[0.6935126185417175, 0.6812443137168884, 0.685...","[{'aspect': 'writing', 'start': 45, 'end': 53,..."
4,I'm not so happy now. I received the shipment ...,"['picture', 'sound']","[[326, 334], [381, 387]]","['Neutral', 'Neutral']","[0.7403015494346619, 0.7675568461418152]","[{'aspect': 'picture', 'start': 326, 'end': 33..."
5,"Didn; t like the movie at first, but after vie...","['setting', 'Days']","[[152, 160], [470, 475]]","['Neutral', 'Neutral']","[0.469528466463089, 0.5733324289321899]","[{'aspect': 'setting', 'start': 152, 'end': 16..."
6,Your face muscles will ache from the many smil...,[],[],[],[],[]
7,Despite some problems (Martin Sheen as Lee mak...,['Martin Sheen'],"[[23, 35]]",['Negative'],[0.5815744400024414],"[{'aspect': 'Martin Sheen', 'start': 23, 'end'..."
8,It was worth the price just to hear Adam West ...,"['Adam West', 'Batman']","[[35, 45], [57, 64]]","['Positive', 'Neutral']","[0.6207146048545837, 0.4886838495731354]","[{'aspect': 'Adam West', 'start': 35, 'end': 4..."
9,Excellent series,['series'],"[[9, 16]]",['Positive'],[0.6286758184432983],"[{'aspect': 'series', 'start': 9, 'end': 16, '..."
10,A good story well done.,['story'],"[[6, 12]]",['Positive'],[0.8458577990531921],"[{'aspect': 'story', 'start': 6, 'end': 12, 'e..."
11,My daughter loves Daniel Tiger and has learned...,[],[],[],[],[]
12,One of the best,[],[],[],[],[]
13,Red Oaks Season 1 was so good that it was inev...,['Red Oaks'],"[[0, 8]]",['Positive'],[0.9315481781959534],"[{'aspect': 'Red Oaks', 'start': 0, 'end': 8, ..."
14,"I ordered a ""new"" DVD set. It was missing Disc...","['DVD', 'Disc', '5']","[[17, 21], [52, 57], [57, 59]]","['Neutral', 'Neutral', 'Negative']","[0.4540269374847412, 0.5021494030952454, 0.495...","[{'aspect': 'DVD', 'start': 17, 'end': 21, 'ex..."
15,These are the guys that do all the Vines. I lo...,['Vines'],"[[190, 196]]",['Neutral'],[0.5160075426101685],"[{'aspect': 'Vines', 'start': 190, 'end': 196,..."
16,was new and wrapped some scruff marks but shou...,[],[],[],[],[]
17,I watched this way back when! I loved it then....,[],[],[],[],[]
18,Very predictable ending,['ending'],"[[16, 23]]",['Negative'],[0.483297199010849],"[{'aspect': 'ending', 'start': 16, 'end': 23, ..."
19,Awesome movie!,['movie'],"[[7, 13]]",['Positive'],[0.9279677867889404],"[{'aspect': 'movie', 'start': 7, 'end': 13, 'e..."
20,Very good. I really enjoyed it.,[],[],[],[],[]
21,This is the only film version of Hamlet I have...,"['acting', 'design', 'costuming', 'Branagh', '...","[[218, 225], [255, 262], [263, 273], [279, 287...","['Neutral', 'Neutral', 'Neutral', 'Neutral', '...","[0.8762566447257996, 0.41335514187812805, 0.82...","[{'aspect': 'acting', 'start': 218, 'end': 225..."
22,What can you say-he was a master performer. I ...,['performer'],"[[32, 42]]",['Positive'],[0.643990159034729],"[{'aspect': 'performer', 'start': 32, 'end': 4..."
23,I really liked Andy Griffith in this movie. Th...,"['plot', 'blazing saddles']","[[47, 52], [150, 166]]","['Negative', 'Neutral']","[0.47921839356422424, 0.7770206928253174]","[{'aspect': 'plot', 'start': 47, 'end': 52, 'e..."
24,Continues to be hilarious,['hilarious'],"[[15, 25]]",['Positive'],[0.7423930764198303],"[{'aspect': 'hilarious', 'start': 15, 'end': 2..."
25,"Very intresting script, good acting, was surpr...","['script', 'acting']","[[15, 22], [28, 35]]","['Neutral', 'Positive']","[0.4887831509113312, 0.4709038734436035]","[{'aspect': 'script', 'start': 15, 'end': 22, ..."
26,great movie but I would have liked to see more...,['movie'],"[[5, 11]]",['Positive'],[0.8300900459289551],"[{'aspect': 'movie', 'start': 5, 'end': 11, 'e..."
27,A good movie with a great theme. Unfortunately...,['officers'],"[[107, 116]]",['Negative'],[0.5197492837905884],"[{'aspect': 'officers', 'start': 107, 'end': 1..."
28,"amazing acting, crazy story but very interesti...",['acting'],"[[7, 14]]",['Positive'],[0.9047906994819641],"[{'aspect': 'acting', 'start': 7, 'end': 14, '..."
29,"I had low expectations to begin with, but it w...",[],[],[],[],[]
30,like it interesting,[],[],[],[],[]
31,This was an absolute favorite of mine growing ...,[],[],[],[],[]
32,Great heart warming story about a dolphin adap...,"['dolphin', 'people', 'marine animal hospital']","[[33, 41], [99, 106], [111, 134]]","['Neutral', 'Neutral', 'Neutral']","[0.6900457143783569, 0.7047964930534363, 0.776...","[{'aspect': 'dolphin', 'start': 33, 'end': 41,..."
33,The cinematography of much of the film was jus...,['cinematography'],"[[3, 18]]",['Neutral'],[0.5261553525924683],"[{'aspect': 'cinematography', 'start': 3, 'end..."
34,A good movie. I'm not sure how close to histor...,['movie'],"[[6, 12]]",['Positive'],[0.8589117527008057],"[{'aspect': 'movie', 'start': 6, 'end': 12, 'e..."
35,Plot is pretty solid. Seems a little disjointe...,"['Plot', 'story', 'acting', 'dialog']","[[0, 4], [89, 95], [110, 117], [163, 170]]","['Neutral', 'Neutral', 'Negative', 'Neutral']","[0.6668266654014587, 0.45574477314949036, 0.47...","[{'aspect': 'Plot', 'start': 0, 'end': 4, 'ext..."
36,DVD had deep scratches in it. Was described as...,['DVD'],"[[0, 3]]",['Negative'],[0.8064640760421753],"[{'aspect': 'DVD', 'start': 0, 'end': 3, 'extr..."
37,This is an awesome movie. This movie will make...,['movie'],"[[18, 24]]",['Positive'],[0.5067189335823059],"[{'aspect': 'movie', 'start': 18, 'end': 24, '..."
38,Great Danish film. This movie is hilarious and...,"['action', 'Lock']","[[46, 53], [73, 78]]","['Positive', 'Neutral']","[0.48063406348228455, 0.48452699184417725]","[{'aspect': 'action', 'start': 46, 'end': 53, ..."
39,First movie was far better. This one was kind ...,[],[],[],[],[]
40,Great movie. Very thought provoking,['movie'],"[[5, 11]]",['Positive'],[0.9204402565956116],"[{'aspect': 'movie', 'start': 5, 'end': 11, 'e..."
41,I used the DVD for a Bible study group. It cam...,['DVD'],"[[10, 14]]",['Positive'],[0.8736011385917664],"[{'aspect': 'DVD', 'start': 10, 'end': 14, 'ex..."
42,Love this movie,['movie'],"[[9, 15]]",['Positive'],[0.9230626821517944],"[{'aspect': 'movie', 'start': 9, 'end': 15, 'e..."
43,I won't review the movie itself. It's a classi...,"['Blu-ray transfer', 'sounds']","[[88, 105], [129, 136]]","['Positive', 'Neutral']","[0.5712125301361084, 0.4978657066822052]","[{'aspect': 'Blu-ray transfer', 'start': 88, '..."
44,A must have for Johnny Maestro fans! Fabulous ...,['Johnny Maestro'],"[[15, 30]]",['Positive'],[0.8791847229003906],"[{'aspect': 'Johnny Maestro', 'start': 15, 'en..."
45,Please get Ashley Darby and her horrible husba...,['Ashley Darby'],"[[10, 23]]",['Negative'],[0.9361638426780701],"[{'aspect': 'Ashley Darby', 'start': 10, 'end'..."
46,"I watched this for the second time tonight, th...",[],[],[],[],[]
47,In some scenes the acting was stiff. Not due t...,"['scenes', 'dialog']","[[7, 14], [120, 127]]","['Neutral', 'Neutral']","[0.4667972922325134, 0.5098398327827454]","[{'aspect': 'scenes', 'start': 7, 'end': 14, '..."
48,I rented this movie and watched it with some c...,['features'],"[[424, 433]]",['Neutral'],[0.5282622575759888],"[{'aspect': 'features', 'start': 424, 'end': 4..."
49,Just finished watching this movie for the firs...,['Diane Franklin'],"[[77, 92]]",['Positive'],[0.8536773920059204],"[{'aspect': 'Diane Franklin', 'start': 77, 'en..."

In [61]:
v3 = pd.read_csv('../results/amazon_absa_v4_aspects.csv')

In [62]:
v3

,review_idx,cluster,aspect,sentiment,mentions,confidence,pct_classifier_fallback,prob_positive,prob_negative,prob_neutral
0,0,0,collection,neutral,1,0.905500,1.0,0.086840,0.007660,0.905500
1,0,1,dvd,neutral,1,0.994639,1.0,0.003588,0.001774,0.994639
2,0,2,gift,positive,1,0.810895,0.0,0.810895,0.094552,0.094552
3,0,3,price,positive,1,0.907941,0.0,0.907941,0.046030,0.046030
4,0,4,deli,positive,1,0.993622,1.0,0.993622,0.002056,0.004321
...,...,...,...,...,...,...,...,...,...,...
122,48,94,rent,neutral,1,0.909154,1.0,0.086415,0.004431,0.909154
123,48,95,special,positive,1,0.960818,1.0,0.960818,0.003998,0.035184
124,48,96,features,positive,1,0.980559,1.0,0.980559,0.002015,0.017426
125,49,9,movie,positive,3,0.941484,1.0,0.658891,0.015970,0.325139
126,49,97,diane franklin,positive,1,0.917315,0.0,0.917315,0.041343,0.041343